config/routes.rb
Rails.application.routes.draw do
  root to: "links#index"
  get '/signup', to: 'users#new'
  post '/users', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  put 'read', to: 'reads#update'

  resources :links, only: [:index, :create, :edit, :update]

  namespace :api do
    namespace :v1 do
      resources :links, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ActiveRecord::Base
  validates :url, :url => true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/api/v1/links_controller.rb
class Api::V1::LinksController < ApplicationController

  def create
    @link = Link.new(link_params)
    if @link.save
      render json: @link, status: 201
    else
      render json: @link.errors.full_messages, status: 500
    end
  end

  private

  def link_params
    params.permit(:title, :url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to '/signup' unless current_user
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_filter :authorize

  def index
    @link = Link.new
    @links = Link.all
  end

  def create
    link = Link.new(link_params)
    if link.save
      redirect_to '/'
    else
      flash[:notice] = "Link not valid format"
      redirect_to '/'
    end
  end

  def edit
    @link = Link.find(params[:id])
  end

  def update
    link = Link.find(params[:id])
    if link.update(link_params)
      redirect_to '/'
    else
      flash[:notice] = "Link not valid format"
      render :edit
    end
  end

  private
  def link_params
    params.require(:link).permit(:url, :title, :read)
  end
end

app/controllers/reads_controller.rb
class ReadsController < ApplicationController

def update
  link = Link.find(params[:id])
  link.update(read: true)
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
      user = User.find_by_email(params[:email])
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to '/'
      else
        redirect_to '/login'
      end
    end

    def destroy
      session[:user_id] = nil
      redirect_to '/'
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>URLockBox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <% if current_user && current_user.id == session[:user_id] %>
  Welcome, <%= current_user.username %>.  <%= link_to "Sign Out", '/logout', method: :get %>
  <% end %>
  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>
</header>
<div class="container">

  <%= yield %>
</div>

</body>
</html>

app/views/links/edit.html.erb
<h2>Submit Link</h2>
<%= form_for(@link) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <%= f.submit "Submit" %>
<% end %>

app/views/links/index.html.erb
<h2>Submit Link</h2>
<%= form_for(@link) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <%= f.submit "Submit" %>
<% end %>

<h2>Your links</h2>
<% @links.each do |link| %>
<div class="links">
  <%= link.title %></br>
  <%= link.url %>
  <%= button_to "Edit", edit_link_path(link), method: :get %>
  <%= button_to "Mark as Read", {:controller => "reads", :action => "update", :id => link.id} , :method=>:put  %>
</div></br>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for :user, url: '/users' do |f| %>

  Username: <%= f.text_field :username %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %>